Fine tune
anarchy-ai/LLM-VM pull request #278
Opened 2023-09-18 11:23 UTC by sushmanthreddy

close #132  

#  Add Fine-tuning and Generation Capabilities to ChatGPT

## Description:

This PR introduces new functionalities to the `ChatGPT` class, allowing users to generate responses using OpenAI's GPT-3.5-turbo model and to fine-tune the model with custom datasets.

## Changes:

1. **Generate Method**: 
   - A new method `generate` has been added to the `ChatGPT` class. 
   - This method takes a prompt and optionally a `max_length` parameter to generate a response using the GPT-3.5-turbo model.
   - Example usage: `SmallLocalOpt.generate("How long does it take for an apple to grow?")`

2. **Fine-tuning Support**:
   - Introduced a `create_conversational_jsonl_file` function to create a temporary JSONL file from a list of conversation pairs. This is essential for the fine-tuning process.
   - Added a `finetune` method to the `ChatGPT` class. This method allows users to fine-tune the GPT-3.5-turbo model with their custom datasets.
   - The method also supports deleting old models post fine-tuning to manage resources effectively.

## Notes:

- The `finetune` method uses a nested `start` function to initiate the fine-tuning process. This design choice was made to encapsulate the fine-tuning logic and make the main method cleaner.
- Global state usage (like `global job_id`) is acknowledged as not being the best practice. This can be refactored in future iterations.

## Testing:

Ensure that you have the necessary credentials and setup to communicate with OpenAI's API. 
1. Test the `generate` method with various prompts to check the response generation capability.
2. Use a sample dataset to test the `finetune` method and verify the model's fine-tuning.

2023-09-18 11:43 UTC, sushmanthreddy commented
hey @VictorOdede can u review this now test file has been added and the new pr with referring to issue 132

2023-09-21 10:54 UTC, VictorOdede commented
PR looks great. Imo, there's no point in using unittest test file since the llm outputs are non-deterministic. You could just include the `test_finetune` function and leave it at that. Also rename the test file to something more specific like `test_gpt3.5_finetune`. After these changes it should be ready to merge 👍

2023-09-23 14:21 UTC, sushmanthreddy commented
@VictorOdede I have made changes as u mentioned ,can u pls review my pull request now ??

2023-09-26 14:26 UTC, sushmanthreddy commented
@VictorOdede any update on this??

2023-09-28 11:06 UTC, VictorOdede commented
PR looks good. LGTM

2023-09-28 11:16 UTC, VictorOdede requested changes

2023-09-28 11:16 UTC, VictorOdede commented on tests/test_gpt3.5_finetune.py
Why are we using unittest? If I understand this correctly, assertions will always fail since generation will be different from asserted value

2023-09-28 11:16 UTC, VictorOdede commented on src/llm_vm/onsite_llm.py
this looks good but you should add  create_conversational_jsonl_file to data synthesis

2023-09-28 12:36 UTC, VictorOdede commented on src/llm_vm/onsite_llm.py
Actually @sushmanthreddy , this is ok as is. just wondering why we cant use the existing `create_jsonl_file` function?

2023-09-28 13:48 UTC, sushmanthreddy commented on src/llm_vm/onsite_llm.py
Both functions have the purpose of creating a temporary JSONL file from a list of data pairs, but they format the data differently. 

1. **`create_jsonl_file`**:
   - Formats each tuple as a simple prompt-completion pair.
   - It's more general and could be used in scenarios other than conversational fine-tuning.
   - Simpler structure, which could be easier for some applications to process.

2. **`create_conversational_jsonl_file`**:
   - Formats the data in a conversational structure.
   - Includes an initial system message that instructs the model to "Complete the prompt as an AI assistant."
   - Better suited for conversational models and tasks since it follows the role-based structure of a dialogue.
   - More complex structure, which might be harder to read manually but provides more context to the model.


- If we are  fine-tuning a model for a chatbot application or a similar conversational AI task, `create_conversational_jsonl_file` might be more appropriate since it adheres to a conversation format that many chatbot platforms expect.
- If we are  working on a more general completion or non-conversational task, `create_jsonl_file` might be more fitting because of its simplicity.

2023-10-02 10:51 UTC, VictorOdede commented on src/llm_vm/onsite_llm.py
ok. looks good to me. we can merge this as soon as you fix the test file

2023-11-28 14:20 UTC, VictorOdede commented
Stale PR

2023-11-28 14:20 UTC, closed without merging