Default Model Details
anarchy-ai/LLM-VM pull request #296
Opened 2023-09-26 11:41 UTC by bilal-aamer

Closes https://github.com/anarchy-ai/LLM-VM/issues/126

2023-09-26 12:22 UTC, bilal-aamer commented
@mmirman @cartazio Kindly review

2023-09-26 13:16 UTC, cartazio commented on README.md
> +| Open Llama | openlm-research/open_llama_3b_v2 | 3B | 6.85 GB |
we dont have this model anymore by default :)

2023-09-26 13:28 UTC, cartazio commented
also backtick quote the URIs

2023-09-26 16:12 UTC, bilal-aamer commented
Done

2023-09-26 16:56 UTC, cartazio commented on model_uri_tables.md
> -|-----|--------------|-----------------------|------------------
why is bloom deleted?

2023-09-26 16:56 UTC, cartazio commented on model_uri_tables.md
> +| bigscience/bloom-1b7/ | 1.7B | 3.4GB   | ❌
nvm, i cant read diffs

2023-09-26 16:58 UTC, bilal-aamer commented
Any problem?

2023-09-27 17:01 UTC, bilal-aamer commented
@cartazio Could you check on this

2023-09-27 17:49 UTC, cartazio commented
Other stuff is priority. Will review when it makes sense

On Wed, Sep 27, 2023 at 1:01 PM Bilal Aamer ***@***.***>
wrote:

> @cartazio <https://github.com/cartazio> Could you check on this
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/anarchy-ai/LLM-VM/pull/296#issuecomment-1737771813>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAABBQX6VG553STLIKXGK2TX4RLX7ANCNFSM6AAAAAA5HSJXH4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-28 05:03 UTC, bilal-aamer commented
Understandable, however this helps beginners in the space understand which model they can use based on the model params, size, etc.

It's addresses the issue #126 which is open for a month now.

2023-10-11 09:58 UTC, VictorOdede requested changes

2023-10-11 09:58 UTC, VictorOdede commented on README.md
i think line 199 should still be `tables in model_uri_tables`

2023-10-11 09:58 UTC, VictorOdede commented on model_uri_tables.md
why did you remove the open-llama table?

2023-10-11 11:30 UTC, bilal-aamer commented on README.md
Was thinking of keeping it either `Model Tables` or `here` keeping it more readable than the `model_uri_tables`

2023-10-11 11:44 UTC, VictorOdede commented on README.md
having the actual file name avoids ambiguity

2023-10-11 11:56 UTC, bilal-aamer commented on README.md
Sure will change it right away.

2023-10-11 15:21 UTC, bilal-aamer commented on README.md
@VictorOdede Done

2023-10-16 16:01 UTC, bilal-aamer commented
@VictorOdede Any update on this?

2023-10-27 16:12 UTC, bilal-aamer commented
@mmirman @VictorOdede This PR is standing for a while now, kindly review

2023-11-06 14:57 UTC, VictorOdede approved these changes

2023-11-06 14:57 UTC, merged