Assign temp var to open ai models
anarchy-ai/LLM-VM pull request #332
Opened 2023-10-14 09:02 UTC by Jobhdez

this fixes #328.

I was able to run the source of error:

```python
>>> from client import Client 
>>> client = Client(big_model='bloom')
`bigscience/bloom-560m` loaded on cuda:0.
`EleutherAI/pythia-70m-deduped` loaded on cuda:0.
Using model: bloom
>>> re = client.complete(prompt = 'What is Anarchy?', context='')
Running with an empty context
>>> re
{'completion': '”\nThe question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is', 'status': 200}
```

2023-10-18 09:28 UTC, Jobhdez commented
@VictorOdede can you review this please if you have time? I also have three others. Thqnks

2023-10-19 09:59 UTC, VictorOdede requested changes

2023-10-19 09:59 UTC, VictorOdede commented on src/llm_vm/onsite_llm.py
we use ctransformers for running hardware-agnostic quantized llms

2023-10-19 12:40 UTC, Jobhdez commented on src/llm_vm/onsite_llm.py
> we use ctransformers for running hardware-agnostic quantized llms

I have addressed your review @VictorOdede

2023-10-26 15:31 UTC, Jobhdez commented
@VictorOdede Hey, lets merge this if you have time.

2023-10-27 13:30 UTC, VictorOdede approved these changes
Looks good!

2023-10-27 13:30 UTC, merged